.TH man 1 "dynperf man page"
.SH NAME
dynperf \- utility to kill some tasks while some other tasks are running 
.SH SYNOPSIS
dynperf [-kill]
.SH DESCRIPTION
dynperf is a utility to kill some tasks while some other tasks are running. Kills unwanted applications while high-performance applications (i.e. video games) are running. 
.SH OPTIONS
Dynperf does not take any options. However, you can supply -kill argument to kill any other running dynperf processes.
.SH AUTHOR
Valters Tomsons (valters.tomsons@protonmail.com)